Add quickstart section at the top of the docs
cpan-authors/IPC-Run pull request #174
Opened 2024-03-17 18:56 UTC by petdance

This is a doc patch to include a quickstart section to the top of the docs, so casual users can get what they need without having to go through the details below.  This is in response to #173.

2024-03-20 02:08 UTC, nmisch requested changes
I like this!  I'll give others some time to review.  In the absence of
objections, I will merge it on or after 2024-03-30.

If you feel like it, regenerate README.md as follows.  Otherwise, I can do it
later.

```
{ head -n3 README.md; pod2markdown lib/IPC/Run.pm; } >README.md.new && \
  mv -f README.md.new README.md
```

2024-03-20 02:08 UTC, nmisch commented on lib/IPC/Run.pm
> +That's the basics of using C<run()> as a replacment for C<system()>. If
s/replacment/replacement/

2024-03-20 14:33 UTC, petdance commented
Thanks, I'm glad you like it. I'll let you take care of the README.md and that "replacment" typo if you don't mind.

2024-03-20 17:12 UTC, nmisch commented
> I'll let you take care of the README.md and that "replacment" typo if you don't mind.

Will do.

2024-03-31 04:01 UTC, nmisch approved these changes

2024-03-31 04:01 UTC, merged